+try

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -21,7 +21,7 @@ jobs:
       HELM_IMAGE: ghcr.io/guybal/tarbac
       VERSION_FILE: VERSION
       HELM_CHART_SUBPATH: config/helm
-      current_branch: feature/helm-oci
+      branch: feature/helm-oci
 
     steps:
       - name: Checkout Code
@@ -29,33 +29,6 @@ jobs:
 
       - name: Set up Docker
         uses: docker/setup-buildx-action@v2
-      
-      - name: Update Version
-        id: bump-version
-        run: |
-
-          current_version=""
-
-          if [ -f "$VERSION_FILE" ]; then
-            current_version=$(cat $VERSION_FILE)
-          else
-            current_version=v1.0.0
-          fi
-
-          echo "current_version=$current_version" >> $GITHUB_ENV
-
-          if [[ "$current_version" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
-            major="${BASH_REMATCH[1]}"
-            minor="${BASH_REMATCH[2]}"
-            patch="${BASH_REMATCH[3]}"
-            new_version="v${major}.${minor}.$((patch + 1))"
-            echo "new_version=$new_version" >> $GITHUB_ENV
-          else
-            echo "Error: Invalid version format $current_version" >&2
-            exit 1
-          fi
-
-          echo "$new_version" > $VERSION_FILE
 
       - name: Generate Code
         run: |
@@ -64,11 +37,6 @@ jobs:
           go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.16.5
           controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./api/v1"
       
-      # - name: Log in to DockerHub
-      #   uses: docker/login-action@v2
-      #   with:
-      #     username: ${{ secrets.DOCKER_USERNAME }}
-      #     password: ${{ secrets.DOCKER_PASSWORD }}
       - name: Log in to GitHub Container Registry
         uses: docker/login-action@v2
         with:
@@ -76,11 +44,46 @@ jobs:
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
+      - name: Update App Version
+        id: bump-app-version
+        run: |
+
+          current_app_version=""
+
+          if [ -f "$VERSION_FILE" ]; then
+            current_app_version=$(cat $VERSION_FILE)
+          else
+            current_app_version=v1.0.0
+          fi
+
+          echo "current_app_version=$current_app_version" >> $GITHUB_ENV
+
+          if [[ "$current_app_version" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
+            major="${BASH_REMATCH[1]}"
+            minor="${BASH_REMATCH[2]}"
+            patch="${BASH_REMATCH[3]}"
+            new_version="v${major}.${minor}.$((patch + 1))"
+            echo "new_version=$new_version" >> $GITHUB_ENV
+          else
+            echo "Error: Invalid version format $current_app_version" >&2
+            exit 1
+          fi
+
+          echo "$new_version" > $VERSION_FILE
+
       - name: Build and Push Docker Image
         run: |
           docker build -t "${DOCKER_IMAGE}:${{ env.new_version }}" .
           docker push "${DOCKER_IMAGE}:${{ env.new_version }}"
 
+      - name: Update Chart Version
+        id: bump-chart-version
+        run: |
+            current_chart_version=$(grep '^version:' $HELM_CHART_SUBPATH/Chart.yaml | awk '{print $2}')
+            new_chart_version=$(echo ${current_chart_version} | awk -F. '{print $1"."$2"."$3+1}')
+            sed -i "s/^version: .*/version: ${new_chart_version}/" $HELM_CHART_SUBPATH/Chart.yaml
+            echo "new_chart_version=$new_chart_version" >> $GITHUB_ENV
+      
       - name: Update Helm Chart
         run: |
           cp -r config/crd/bases/* config/helm/templates/crd/
@@ -94,20 +97,20 @@ jobs:
       - name: Push Helm Chart as OCI Image
         run: |
           mkdir -p temp-helm-oci
-          helm package ${HELM_CHART_SUBPATH} --destination ./temp-helm-oci
+          helm package ${HELM_CHART_SUBPATH} --app-version ${{ env.new_version }} --destination ./temp-helm-oci
           # echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin
           CHART_PACKAGE=$(ls ./temp-helm-oci/*.tgz)
           helm push ${CHART_PACKAGE} oci://${HELM_IMAGE} 
 
       - name: Commit Version Changes
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        # env:
+        #   GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           git config user.name "GitHub Actions"
           git config user.email "actions@github.com"
-          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/guybal/tarbac.git
+          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/guybal/tarbac.git
           git add $VERSION_FILE $HELM_CHART_SUBPATH/Chart.yaml $HELM_CHART_SUBPATH/values.yaml
           git add config/helm/templates/crd
           git commit -m "Update to version ${{ env.new_version }}"
           git tag -a ${{ env.new_version }} -m "${{ env.new_version }}" 
-          git push --follow-tags origin ${{ env.current_branch }}
+          git push --follow-tags origin ${{ env.branch }}
