+ try

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -20,32 +20,32 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v3
 
-      - name: Set up Docker
-        uses: docker/setup-buildx-action@v2
+      # - name: Set up Docker
+      #   uses: docker/setup-buildx-action@v2
       
-      - name: Update Version
-        id: bump-version
-        run: |
-          if [ -f "$VERSION_FILE" ]; then
-            echo "current_version=$(cat $VERSION_FILE)" >> $GITHUB_ENV
-          else
-            echo "current_version=v1.0.0" >> $GITHUB_ENV
-          fi
+      # - name: Update Version
+      #   id: bump-version
+      #   run: |
+      #     if [ -f "$VERSION_FILE" ]; then
+      #       echo "current_version=$(cat $VERSION_FILE)" >> $GITHUB_ENV
+      #     else
+      #       echo "current_version=v1.0.0" >> $GITHUB_ENV
+      #     fi
 
-          current_version="${{ env.current_version }}"
+      #     current_version="${{ env.current_version }}"
 
-          if [[ "$current_version" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
-            major="${BASH_REMATCH[1]}"
-            minor="${BASH_REMATCH[2]}"
-            patch="${BASH_REMATCH[3]}"
-            new_version="v${major}.${minor}.$((patch + 1))"
-            echo "new_version=$new_version" >> $GITHUB_ENV
-          else
-            echo "Error: Invalid version format $current_version" >&2
-            exit 1
-          fi
+      #     if [[ "$current_version" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
+      #       major="${BASH_REMATCH[1]}"
+      #       minor="${BASH_REMATCH[2]}"
+      #       patch="${BASH_REMATCH[3]}"
+      #       new_version="v${major}.${minor}.$((patch + 1))"
+      #       echo "new_version=$new_version" >> $GITHUB_ENV
+      #     else
+      #       echo "Error: Invalid version format $current_version" >&2
+      #       exit 1
+      #     fi
 
-          echo "${{ env.new_version }}" > $VERSION_FILE
+      #     echo "${{ env.new_version }}" > $VERSION_FILE
 
       # - name: Generate Code
       #   run: |
